### ISSUE TITLE
Questions about gumble_ffmpeg changes

### ISSUE THREAD

**Issue by matthieugrieger** [layeh/gumble#16]
Hi there,

I have some questions about how gumble_ffmpeg works now since it seems to have been reworked.

1) Since the arguments to `Play()` have been removed, does `SourceFile()` need to be used to specify the file to stream from? Whenever I use this function I get a "nil source" error even though the source file definitely exists. The audio player example project just passes the filename to the `Play()` function, but I think it might be outdated.

2)  What is the correct way to do callbacks after the song has finished? It used to be passed into `Play()` as well but now I'm guessing you have to use `Wait()` in some fashion?

Thanks!

**Comment by bontibon** [comment]
>  does SourceFile() need to be used to specify the file to stream from?

Yes.  Here is an example:

```go
stream := gumble_ffmpeg.New(client)
stream.Source = gumble_ffmpeg.SourceFile("myfile.mp3")
stream.Play()
```

> The audio player example project just passes the filename to the Play() function, but I think it might be outdated.

I need to fix that. Thank you for the reminder.

> What is the correct way to do callbacks after the song has finished?

```go
// ...
stream.Play()
go func() {
   stream.Wait()
   mycallbackfunc()
} ()
```

**Comment by matthieugrieger** [comment]
Thanks for the response!

**Comment by matthieugrieger** [comment]
Awesome, I've got it working now!
