### ISSUE TITLE
Unable to install opus

### ISSUE THREAD

**Issue by jcdesimp** [layeh/gumble#18]
When I attempt to run `go get "github.com/layeh/gumble/opus"` I get the following error:

```
# github.com/layeh/gumble/opus
../../../github.com/layeh/gumble/opus/opus.go:54: e.Encoder.ResetState undefined (type *gopus.Encoder has no field or method ResetState)
```

I figure I must be doing something wrong but I can't figure out how to resolve it.

I'm developing on Mac OS X 10.11.4 Beta
go version go1.5.2 darwin/amd64

**Comment by bontibon** [comment]
Rerun that command after executing the following:

    go get -u github.com/layeh/gopus

**Comment by bontibon** [comment]
Also, pass the `-u` flag when you `go get`:

    go get -u "github.com/layeh/gumble/opus"

**Comment by jcdesimp** [comment]
Ahh ok got it thanks!
