### ISSUE TITLE
Sound not transmitting when connected to remote server.

### ISSUE THREAD

**Issue by jcdesimp** [layeh/gumble#20]
I'm getting some very strange behavior. When attempting to play a sound, the sound often does not transmit at all when gumble is connected to a remote server, though sometimes it does work. However, if it's connected to a murmur instance running locally (i.e. "localhost") then sounds seem to play just fine. There don't appear to be any errors at all when this happens. Any thing I could be missing? Thanks!

**Comment by matthieugrieger** [comment]
Do you have `opusthreshold=0` in your Mumble server's ini configuration?

**Comment by jcdesimp** [comment]
@matthieugrieger ahh that was it, thank you.

**Comment by matthieugrieger** [comment]
No problem. :)
