### ISSUE TITLE
gumbleffmpeg: state is not set to StateInitial on newly created streams

### ISSUE THREAD

**Issue by neckcen** [layeh/gumble#21]
On a newly created stream, `state` is equal to 0. This does not match `StateInitial` which equals 1.

As a result the [check on line 134](https://github.com/layeh/gumble/blob/98ab1a2ab5cdb1a498807da66a83e2bf1b345f4d/gumbleffmpeg/stream.go#L134) fails for newly created streams. Consequently calling `Stop()` before `Play()` causes a runtime error.

**Comment by bontibon** [comment]
Thank you for the bug report.
