### ISSUE TITLE
Stream.Stopsource()

### ISSUE THREAD

**Issue by bgunebakan** [layeh/gumble#23]
Hi,
When using barnard, i a press F1 to stop stream and then press again to start stream there is no sound.startSource just work before the StopSource.What is the problem ? 

Regards..

**Comment by bgunebakan** [comment]
We are using it in Raspberry pi.

**Comment by bontibon** [comment]
Questions about barnard should be posted on barnard's issue tracker: https://github.com/layeh/barnard/issues

Furthermore, I don't understand what your question.
