### ISSUE TITLE
Issues with user methods

### ISSUE THREAD

**Issue by matthieugrieger** [layeh/gumble#25]
Hi there,

I'm having some issues with the User methods, specifically `Move()` and `SetComment()`. I am in the process of refactoring MumbleDJ, and in the process I have been updating to incorporate the new API changes to Gumble. Nothing happens when I call the `Move()` and `SetComment()` commands, even though the `Self` user is valid. Is there something I'm doing wrong here?

I've made sure to wrap these function calls in `Do()` calls, but that doesn't seem to help.

As an example, here is a snippet of code that shows how I'm using these methods: https://github.com/matthieugrieger/mumbledj/blob/refactor/main.go#L143-L152

I connect to the server and set the Client here if that helps at all: https://github.com/matthieugrieger/mumbledj/blob/refactor/bot/mumbledj.go#L164-L210

Thanks!

**Comment by bontibon** [comment]
The problem in that your `MumbleDJ.Connect` function doesn't return back to the main function: 
https://github.com/matthieugrieger/mumbledj/blob/refactor/bot/mumbledj.go#L207

**Comment by matthieugrieger** [comment]
Awesome, that fixed it. I knew I was missing something...
