### ISSUE TITLE
Feature checklist

### ISSUE THREAD

**Issue by Yamakaky** [layeh/gumble#33]
I would like to make a headless mumble client with remote control (can be RPC, REST and/or chat message) which would output the audio from a Mumble channel to [Liquidsoap](http://liquidsoap.fm/doc-1.2.1/reference.html#Source___Input) (ALSA or pulseaudio is fine, there is also a HTTP input but I don't know how it works). I don't need to play anything in the channel, it's just Mumble -> Liquidsoap. Do you think your library would be appropriate for that?

For the background, I'm doing a web radio with lives recording from Mumble. I currently launch Mumble in a VNC session, but it's not very handy and I can't control it remotely.

**Comment by bontibon** [comment]
> Do you think your library would be appropriate for that?

Not sure. It's possible that the gumble openal package would be able to redirect the audio correctly.
