### ISSUE TITLE
running the mumble-audio-player on windows does not play sound

### ISSUE THREAD

**Issue by momo-aux** [layeh/gumble#35]
I get no error message but also hear no sound.
I used the chimes.ogg file.

I used minGW64 on windows for the go build.
I can start the exe and it connects to my server.
If I send the text: chimes.ogg it says: Playing chimes.ogg on the shell window but I can't hear sound.
If I move the bot, I hear the text to speach message from the server, so audio ist enabled and working.

Any hints how to debug or what to change?

**Comment by bontibon** [comment]
What Mumble client version are you running?

**Comment by momo-aux** [comment]
Newest from mumble website, installed and download on monday.

**Comment by momo-aux** [comment]
same result on ubuntu, no error but no sound

**Comment by momo-aux** [comment]
ffmpeg -i chimes.ogg -f pulse "stream" plays the sound locally, so sound setting and ffmpeg are working.

**Comment by momo-aux** [comment]
Currently testing with version 1.2.19. Also tested MumbleDJ with that version, also no sound.

**Comment by bontibon** [comment]
Things to test:

1. Check the bot's idle time when transmitting audio (right click bot in Mumble and click Information. The idle time should be 0s when audio is being received).

2. Try another server and/or client to see if there is some unknown setting that is preventing you from hearing the bot's audio.

**Comment by momo-aux** [comment]
you are right, it's idling.
And yes, it's working on another server.
So yes, the problem is my server, but what is wrong :-)
Any hints how to check that?

**Comment by momo-aux** [comment]
Ah guess it's a code problem. the server I use is an ubuntu mumble 1.2.3 with Celtic codec.

**Comment by bontibon** [comment]
Yes, CELT is the problem. gumble only supports Opus, so please upgrade to Mumble server 1.2.4 or above.
