### ISSUE TITLE
how to join a channel with gumble lib

### ISSUE THREAD

**Issue by Tux04** [layeh/gumble#40]
41/5000
how does a user change the channel in gumble ? 
63/5000
with which function a user changes to another channel?

**Comment by bontibon** [comment]
```go
channel := client.Channels.Find("Root Channel", "sub channel", ...)
if channel != nil {
    client.Self.Move(channel)
}
```

**Comment by Tux04** [comment]
Thank you for your help, you have helped me a lot !!!

regards

Dirk

**Comment by s3m1s0n1c** [comment]
Is there any reason why this doesn't go to root/sub/sub channels

Say i wanna go to Channel B  I use -channel "Channel B" and it says Unable to find Channel B

Root
Channel 1
   Channel A
   Channel B
Channel 2


 ```
channel := b.Client.Channels.Find(ChannelName)
        if channel != nil {
        fmt.Printf("Move Channel Name: %s\n", channel)
                b.Client.Self.Move(channel)
        } else {
                fmt.Printf("Unable to find channel: %s\n", ChannelName)
        }

```

**Comment by bontibon** [comment]
@s3m1s0n1c Mumble channels have a tree structure, so you need to specify the complete "path" to the channel from the root.

If you just want to join any channel with that name, you could try something like:
```go
for _, channel := range b.Client.Channels {
    if channel.Name == ChannelName {
        b.Client.Self.Move(channel)
        break
    }
}
```

**Comment by s3m1s0n1c** [comment]
Thanks Works a treat 👍

**Comment by s3m1s0n1c** [comment]
Could the following code be added to client.go for next release

Delete from line 121 -> 123
and add the following

for _, channel := range b.Client.Channels {
    if channel.Name == ChannelName {
        b.Client.Self.Move(channel)
        break
    }
}
