### ISSUE TITLE
Client loses ability to send message to channel

### ISSUE THREAD

**Issue by Stieneee** [layeh/gumble#55]
I am having an issue with Gumble clients lose the ability to send messages to channels. The issue seems to happen after longer periods of connectivity > 1 hrs but usually < 24 hrs.

I first started to see this issue in a project I have been working on [Mumble-Discord-Bridge ](https://github.com/Stieneee/mumble-discord-bridge) and have since reproduced using a simpler project [Gumble-Echo-Test](https://github.com/Stieneee/gumble-echo-test). The behavior has been relatively predictable over the last couple of months and I have only occasionally tried to track down the issue.

After an initial review of the Gumble code, I can't see how this client would be causing this issue.

The Mumble codebase appears to be more complex with more opportunities to drop the message.

I thought I bring the issue up here and offer others a chance to try and reproduce the issue before creating an Issue in the Mumble project itself.

**Comment by ghost** [comment]
Looks like this could have been a bug with the Mumble server. See https://github.com/mumble-voip/mumble/issues/4578.

**Comment by Stieneee** [comment]
Confirmed. I updated to murmur 1.3.4 from 1.3.0 and have not seen the issue again. Thanks for your time.
