### ISSUE TITLE
will there be a gumble_libav ?

### ISSUE THREAD

**Issue by hamilton5** [layeh/gumble#8]
will you be supporting ffmpeg in the future, any plans for libav ?

**Comment by bontibon** [comment]
> will you be supporting ffmpeg in the future

Yes; I do not plan on discontinuing support for [gumble_ffmpeg](https://github.com/layeh/gumble/tree/master/gumble_ffmpeg).

> any plans for libav ?

I currently have no plans for writing another audio module for gumble.

**Comment by bontibon** [comment]
It should now be possible to use `avconv` instead of `ffmpeg` with 8f7277e3e110aa653534702e1871026208013533.
